### PR TITLE
Fix page focus flicker

### LINKED ISSUE #44: Page focus flickers every second
Minor thing, not quite sure of its effects yet. It might be nothing.

### PR DESCRIPTION
**Pull request by graysonwright**
The one-second state update on `App`
was causing the `Order` component to re-render.

Moving the one-second updates to `Lobby` fixes the issue.

Fixes #44.

### CODE REVIEW

File: app/javascript/components/Lobby.js [hunk 1]
```diff
@@ -9,27 +10,51 @@ const service_directory = {
...
+  componentWillUnmount() {
+    clearInterval(this.timer)
+  }
+
+  render() {
+    return (
+      <Layout position={this.props.position}>
+        { Object.keys(service_directory).map((service_name) => (
+          <Service key={service_name}>
+            <Emoji>{ service_directory[service_name] }</Emoji>
```
Comment (MattyAyOh) [inline app/javascript/components/Lobby.js]: did you make a custom html tag?  or what is this?

Comment (graysonwright) [reply app/javascript/components/Lobby.js]: It's a React component - essentially a custom HTML tag that has javascript behaviors and styling built-in.

https://reactjs.org/

thefuture

Comment (graysonwright) [reply app/javascript/components/Lobby.js]: Also see https://www.styled-components.com/ for the styling part of it.
